apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: slides
  namespace: deckhub
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: slides
    spec:
      containers:
      - image: deckhub/slides:1.0.0-alpha2
        imagePullPolicy: Always
        name: slides
        env:
          - name: Runtime__PathBase
            value: '/slides'
          - name: Security__ApiKeyHashPhrase
            valueFrom:
              secretKeyRef:
                name: api-key
                key: hashPhrase
          - name: Storage__ConnectionString
            valueFrom:
              secretKeyRef:
                name: slide-storage
                key: connstr
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: slides
  namespace: deckhub
spec:
  ports:
  - port: 80
    protocol: TCP
    name: http
  selector:
    app: slides
  sessionAffinity: ClientIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: slides
  namespace: deckhub
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: deckhub.app
    http:
      paths:
      - path: /slides
        backend:
          serviceName: slides
          servicePort: 80
