apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: slides
  namespace: shtik
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: slides
    spec:
      containers:
      - image: shtik/slides:1.1.0
        imagePullPolicy: Always
        name: slides
        env:
          - name: Storage__ConnectionString
            valueFrom:
              secretKeyRef:
                name: slide-storage
                key: connstr
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: slides
  namespace: shtik
spec:
  ports:
  - port: 80
    protocol: TCP
    name: http
  selector:
    app: slides